- name: handlers, configuration nginx in server
  hosts: server2
  remote_user: yc-user
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.apt:
          name: nginx
          state: present
      
    - name: copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html 

    - name: copy nginx config 
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx 
    
  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx 
        state: restarted
    
