- name: configuration nginx with variables
  hosts: server2 
  remote_user: yc-user
  become: yes
  vars: 
    nginx_port: 80
    root_dir: /usr/share/nginx/
  
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx 
        state: present
      
    - name: copy index html using variables
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/html/index.html"
      
    - name: configure nginx with variables and templates
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

  handlers:
    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
